---
apiVersion: v1
kind: Namespace
metadata:
  name: innsecure
  labels:
    name: innsecure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: innsecure-config
  labels:
    app: innsecure
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: YWRtaW4xMjM0
  DB_HOST: db
  DB_USER: root
  DB_PASSWORD: cGFzc3dvcmQ=
  JWT_SIGNING_STRING: SigningString